Funcionalidade de Notificação
LIFeSUFSCAR/APP-MENTAL pull request #12
Opened 2023-03-17 19:27 UTC by LuisRotoly

Criada funcionalidade que verifica se há alguma atividade dentre Questionários, Diário do sono e Leituras que são novas ou que devem ser feitas/finalizadas.
Todo novo questionário terá uma notificação na data que o mesmo estará disponível e todo dia as 7h o usuário receberá a notificação do diário do sono.
Nos cards do Home ficará visivel uma bolinha vermelha com a numeração de quantas atividades são novas para serem feitas. Na lista de questionários tambem aparecerá a mesma bolinha vermelha enquanto o questionário não for respondido.
Falta promover o mesmo desfecho com as leituras, mas essas dependem de outra tarefa.

2023-03-17 23:21 UTC, gudominguete requested changes

2023-03-17 23:21 UTC, gudominguete commented on lib/Screens/Home/Widgets/body.dart
> +            sleepNotification = 0;
O que representa cada numero?

2023-03-17 23:21 UTC, gudominguete commented on lib/Screens/Home/Widgets/main_card_button.dart
> +    return notification != 0
trocar para > 0

2023-03-17 23:21 UTC, gudominguete commented on lib/Screens/Questionarie/Widgets/app_body_widget.dart
> +                      /*Expanded(
Pode remover?

2023-03-20 14:14 UTC, LuisRotoly commented on lib/Screens/Home/Widgets/body.dart
> +            sleepNotification = 0;
Se o diario do sono já foi respondido hoje ele seta a notificação para 0 (meio que um falso), se não foi respondida ele seta como 1. Como o diario do sono não tem mais de uma ação então o unico valor possivel é 1, não tem como dar 2,3,4,5...

2023-03-20 22:29 UTC, gudominguete commented on lib/Screens/Home/Widgets/body.dart
> +            sleepNotification = 0;
melhor trocar para boolean, nao?

2023-03-20 22:33 UTC, gudominguete requested changes

2023-03-20 22:33 UTC, gudominguete commented on lib/Screens/Home/Widgets/body.dart
> +            sleepNotification = 0;
e mudar o nome tbm para algo que remeta a leitura da notificacao

2023-03-21 18:16 UTC, LuisRotoly commented on lib/Screens/Home/Widgets/body.dart
> +            sleepNotification = 0;
Troquei os nomes mas não posso trocar para boolean, o parametro que é usado dos outros é int

2023-03-21 23:59 UTC, gudominguete requested changes

2023-03-21 23:59 UTC, gudominguete commented on lib/Screens/Home/Widgets/body.dart
> +            isSleepDiaryAnsweredToday = 0;
Esse atributo será somente para o SleepDiary?

2023-03-22 16:32 UTC, LuisRotoly commented on lib/Screens/Home/Widgets/body.dart
> +            isSleepDiaryAnsweredToday = 0;
Tem 3 atributos para receber se tem uma ou mais tarefa a ser feita ou não. Essa em especifico é só pra SleepDiary.

2023-03-23 23:32 UTC, gudominguete commented on lib/Screens/Home/Widgets/body.dart
> +            isSleepDiaryAnsweredToday = 0;
Se for so para o SleepDiary e representa se ja foi respondido, eh melhor trocar pra bool, nao?

2023-03-24 13:16 UTC, LuisRotoly commented on lib/Screens/Home/Widgets/body.dart
> +            isSleepDiaryAnsweredToday = 0;
alterado nome

2023-03-30 00:46 UTC, gudominguete requested changes

2023-03-30 00:46 UTC, gudominguete commented on lib/Screens/SignIn/signin.dart
> +  updateUserToken(String userEmail) async {
Colocar o token junto com a função de login

2023-04-04 17:19 UTC, gudominguete approved these changes

2023-04-04 18:01 UTC, merged