Leituras recomendadas mapeada para o novo backend
LIFeSUFSCAR/APP-MENTAL pull request #13
Opened 2023-03-22 16:19 UTC by LuisRotoly

- Entrar nas novas leituras (caso não tenha nenhum dado no seu banco de dados local ele vai pegar os dados do servidor e colocar no banco local. Para futuras alterações no banco de dados local será perguntado para o usuário se o mesmo quer atualizar ou não o banco).
- Entrar em uma leitura com texto.
- Entrar em uma leitura com video e verificar se o mesmo vai rodar.(A ultima leitura do ultimo grupo é um video)

2023-03-23 23:40 UTC, gudominguete requested changes

2023-03-23 23:40 UTC, gudominguete commented on lib/Screens/Reading/Widgets/group_body.dart
> +class GroupBody extends StatefulWidget {
O que seria essa classe?

2023-03-23 23:40 UTC, gudominguete commented on lib/Screens/Reading/Widgets/group_body.dart
> +class IntervCard extends StatelessWidget {
Separar em outro arquivo

2023-03-23 23:40 UTC, gudominguete commented on lib/Screens/Reading/Widgets/group_body.dart
> +              return this.reading.type != "V"
Criar um enum

2023-03-23 23:40 UTC, gudominguete commented on lib/Screens/Reading/Widgets/img_and_text_info.dart
>  class ImageCard extends StatelessWidget {
Separar cada classe em um arquivo diferente

2023-03-23 23:40 UTC, gudominguete commented on lib/Screens/Reading/recomended_readings.dart
> +  List<String> groupList = [];
trocar para readingGroupList

2023-03-23 23:40 UTC, gudominguete commented on lib/Screens/Reading/recomended_readings.dart
> +              ReadingDatabase.instance.dropAllRows().then((_) {
Modularizar as funções dentro do onPressed

2023-03-24 17:34 UTC, LuisRotoly commented on lib/Screens/Reading/Widgets/group_body.dart
> +              return this.reading.type != "V"
Não usa mais

2023-03-24 20:06 UTC, LuisRotoly commented on lib/Screens/Reading/Widgets/group_body.dart
> +class GroupBody extends StatefulWidget {
Todos os nomes de classe e a sua estrutura foram modificados

2023-03-24 23:32 UTC, gudominguete commented on lib/Screens/Reading/Widgets/group_body.dart
> +class GroupBody extends StatefulWidget {
Coloca algo especifico da leitura, nao sei se Body eh um nome bom aqui

2023-03-27 11:01 UTC, LuisRotoly commented on lib/Screens/Reading/Widgets/group_body.dart
> +class GroupBody extends StatefulWidget {
Essa classe não existe mais com esse nome

2023-03-27 22:57 UTC, gudominguete approved these changes

2023-03-29 16:51 UTC, merged