Adicionado lembrar das credenciais do login
LIFeSUFSCAR/APP-MENTAL pull request #20
Opened 2023-04-17 18:45 UTC by LuisRotoly

Adicionada funcionalidade de lembrar das credenciais do login do usuário
![Screenshot_2023-04-17-15-44-25-957_com ufscar app_mental](https://user-images.githubusercontent.com/109184689/232581665-83a66a24-2ee9-4bfd-8215-e659848bbf37.jpg)

2023-04-17 23:15 UTC, gudominguete requested changes

2023-04-17 23:15 UTC, gudominguete commented on lib/Screens/SignIn/signin.dart
> +  List<String> userAndPasswordStored = [];
Pq uma lista de String?

2023-04-17 23:15 UTC, gudominguete commented on lib/Screens/SignIn/signin.dart
> +    if (checkboxValue) {
Mudar o nome para algo isRememberPassword

2023-04-17 23:15 UTC, gudominguete commented on lib/Screens/SignIn/signin.dart
> +                                setState(() {
Trocar para função

2023-04-18 15:35 UTC, LuisRotoly commented on lib/Screens/SignIn/signin.dart
> +  List<String> userAndPasswordStored = [];
Por que eu preciso salvar o login e a senha e só consigo salvar no sharedPreferences ou uma string ou uma lista de string, como são duas strings preferi usar a lista

2023-04-19 00:55 UTC, gudominguete commented on lib/Screens/SignIn/signin.dart
> +  List<String> userAndPasswordStored = [];
Com hashmap ou map nao da?

2023-04-19 20:04 UTC, LuisRotoly commented on lib/Screens/SignIn/signin.dart
> +  List<String> userAndPasswordStored = [];
Não tenho essa opção, tenho como setar pra bool, double, int, string e string list.

2023-04-19 22:19 UTC, gudominguete commented on lib/Screens/SignIn/signin.dart
> +  List<String> userAndPasswordStored = [];
Minha ideia é no lugar de ter uma lista de só duas posições, vc marcar um map<String,Bool>  que para cada email vc marca se é pra salvar ou não

2023-04-22 01:04 UTC, gudominguete approved these changes

2023-04-24 11:55 UTC, merged