Contatos importados do telefone do usuário
LIFeSUFSCAR/APP-MENTAL pull request #22
Opened 2023-04-19 20:15 UTC by LuisRotoly

Nova funcionalidade criada para importar contatos do telefone do usuário.

![Screenshot_2023-04-19-16-44-43-315_com ufscar app_mental](https://user-images.githubusercontent.com/109184689/233189465-63eafe64-8a7a-4157-ad64-65ebc9fedf44.jpg)
![Screenshot_2023-04-19-16-48-29-247_com ufscar app_mental](https://user-images.githubusercontent.com/109184689/233189452-690b1273-ad50-4231-b2b2-db5b977d0830.jpg)

2023-04-19 22:23 UTC, gudominguete requested changes

2023-04-19 22:23 UTC, gudominguete commented on lib/Screens/Contacts/Widgets/checkbox_contact.dart
> +  final bool checkedValue;
Qual seria o campo checkbox?

2023-04-19 22:23 UTC, gudominguete commented on lib/Screens/Contacts/Widgets/checkbox_contact.dart
> +  final int index;
indice do que?

2023-04-19 22:23 UTC, gudominguete commented on lib/Screens/Contacts/Widgets/import_contact.dart
> +  List<bool> checkedValue = [];
Qual seria o objetivo dessa lista?

2023-04-19 22:23 UTC, gudominguete commented on lib/Screens/Contacts/Widgets/new_contact.dart
Pq deletou esse arquivo?

2023-04-19 22:23 UTC, gudominguete commented on lib/Screens/Contacts/contacts_screen.dart
> +        list.sort((a, b) => a.displayName.compareTo(b.displayName));
o que é a e b?

2023-04-19 22:23 UTC, gudominguete approved these changes

2023-04-20 12:09 UTC, LuisRotoly commented on lib/Screens/Contacts/Widgets/new_contact.dart
o arquivo não estava sendo usado

2023-04-20 12:16 UTC, LuisRotoly commented on lib/Screens/Contacts/Widgets/checkbox_contact.dart
> +  final bool checkedValue;
que?

2023-04-20 12:18 UTC, LuisRotoly commented on lib/Screens/Contacts/Widgets/checkbox_contact.dart
> +  final int index;
alterei o nome

2023-04-20 12:19 UTC, LuisRotoly commented on lib/Screens/Contacts/Widgets/import_contact.dart
> +  List<bool> checkedValue = [];
Lista para guardar todos os booleanos dos checkbox e depois pego os nomes e os numeros de telefones para mandar pro banco de dados usando ela como base.

2023-04-20 12:22 UTC, LuisRotoly commented on lib/Screens/Contacts/contacts_screen.dart
> +        list.sort((a, b) => a.displayName.compareTo(b.displayName));
É a maneira padrão que é feita a ordenação, seria um contato A e um contato B. Os contatos vindos do telefone não vem ordenados via nome, então faço a ordenação pra ficar mais fácil

2023-04-22 01:06 UTC, gudominguete commented on lib/Screens/Contacts/Widgets/checkbox_contact.dart
> +  final bool checkedValue;
O nome ta muito generico, qual seria a função desse checkbox?

2023-04-22 01:06 UTC, gudominguete commented on lib/Screens/Contacts/Widgets/import_contact.dart
> +  List<bool> checkedValue = [];
Mudar o nome para algo que faça mais sentido com a funcionalidade da variavel

2023-04-22 01:07 UTC, gudominguete commented on lib/Screens/Contacts/contacts_screen.dart
> +        list.sort((a, b) => a.displayName.compareTo(b.displayName));
Mudar os nomes das variaveis para contatoA e contatoB, ou algo que faça mais sentido

2023-04-24 18:28 UTC, LuisRotoly commented on lib/Screens/Contacts/Widgets/checkbox_contact.dart
> +  final bool checkedValue;
é o booleano que dá valor true ou false pro checkbox

2023-04-24 18:30 UTC, LuisRotoly commented on lib/Screens/Contacts/Widgets/import_contact.dart
> +  List<bool> checkedValue = [];
mudei para isCheckedList

2023-04-24 23:15 UTC, merged