Notificacao feita no chat
LIFeSUFSCAR/APP-MENTAL pull request #28
Opened 2023-04-28 17:55 UTC by LuisRotoly

Agora aparecem as bolinhas vermelhar com quantidade indicando que há mensagens no chat para serem lidar.
A notificação só desaparece depois que o usuário entra no chat daquele respectivo pesquisador.

2023-04-29 13:40 UTC, gudominguete requested changes

2023-04-29 13:40 UTC, gudominguete commented on lib/Screens/ChatPage/ChatPage.dart
> +                  .popUntil(ModalRoute.withName('/logged-home'));
Criar função fora do onPressed

2023-04-29 13:40 UTC, gudominguete commented on lib/Screens/ChatRoom/chatRoomsScreen.dart
> +            Navigator.of(context).popUntil(ModalRoute.withName('/logged-home'));
Criar função fora do onPressed

2023-04-29 13:40 UTC, gudominguete commented on lib/Screens/ChatRoom/chatRoomsScreen.dart
> +  static const routeName = '/chat-room-screen';
Está sendo usada?

2023-04-29 13:40 UTC, gudominguete commented on lib/Screens/Contacts/contact_chat_screen.dart
> +            Navigator.of(context).popUntil(ModalRoute.withName('/logged-home'));
Criar função fora do onPressed

2023-04-29 13:40 UTC, gudominguete commented on lib/Screens/ResetPassword/reset_password.dart
> +                          Navigator.pop(context);
Criar função fora do onTap

2023-04-29 13:40 UTC, gudominguete commented on lib/Screens/SignIn/signin.dart
> +    //final fcmToken = await FirebaseMessaging.instance.getToken();
Esse não pode remover ne?

2023-04-29 13:40 UTC, gudominguete commented on lib/Screens/Tutorial/tutorial_screen.dart
> +              Navigator.of(context)
Criar função fora do onPressed

2023-05-02 13:03 UTC, LuisRotoly commented on lib/Screens/ChatRoom/chatRoomsScreen.dart
> +  static const routeName = '/chat-room-screen';
tá sim

2023-05-02 13:05 UTC, LuisRotoly commented on lib/Screens/SignIn/signin.dart
> +    //final fcmToken = await FirebaseMessaging.instance.getToken();
não esse funciona com o firebase, mas tá comentado por que está dando problema no ios seus.
a difrerença entre os dois foi um espaço, por isso apareceu no PR

2023-05-02 23:08 UTC, gudominguete approved these changes

2023-05-03 19:37 UTC, merged