Jogo da memória criado
LIFeSUFSCAR/APP-MENTAL pull request #31
Opened 2023-05-03 18:38 UTC by LuisRotoly

Criado o jogo da memória.
O jogo se encontra na drawer para ser selecionado.
Ao iniciar o jogo aguarda 10seg com as cartas viradas para cima.
![Screenshot_2023-05-03-15-02-10-173_com ufscar app_mental](https://user-images.githubusercontent.com/109184689/236011362-413d9583-2ce4-41b5-be3a-21b93eb6e491.jpg)

Logo após as cartas são viradas para baixo e o usuário pode selecionar as cartas para verificar se são pares.
![Screenshot_2023-05-03-15-02-29-866_com ufscar app_mental](https://user-images.githubusercontent.com/109184689/236011366-f180ef05-6bc4-43d2-ab50-3ed4310a6c08.jpg)

Ao final é possível jogar novamente ou sair do jogo.
![Screenshot_2023-05-03-15-02-49-198_com ufscar app_mental](https://user-images.githubusercontent.com/109184689/236011372-279c9d7e-83ae-4f01-a0f5-d46869cadeef.jpg)

Tambem é possível dar zoom para visualizar melhor os escritos da carta.
![Screenshot_2023-05-03-15-03-34-678_com ufscar app_mental](https://user-images.githubusercontent.com/109184689/236011375-66f8a05d-cf5f-4096-ba2a-c97fdf172c3a.jpg)

2023-05-04 00:06 UTC, gudominguete requested changes

2023-05-04 00:06 UTC, gudominguete commented on lib/Screens/MemoryGamePage/memory_game_body.dart
> +  List<String> randomicTextList = List<String>.filled(8, "");
Esse 8 será diferente do tamanho de textList?

2023-05-04 00:06 UTC, gudominguete commented on lib/Screens/MemoryGamePage/memory_game_body.dart
> +    for (int i = 0; i < 8; i++)
Usar o 8 como variavel statica ou parametrizada(tamanho do vetor utilizado acima)

2023-05-04 00:06 UTC, gudominguete commented on lib/Screens/MemoryGamePage/memory_game_body.dart
> +        angleCard[i] = pi % (2 * pi);
O que seria pi?

2023-05-04 00:06 UTC, gudominguete commented on lib/Screens/MemoryGamePage/memory_game_body.dart
> +        angleCard[i] = pi % (2 * pi);
Seria a constante Pi?

2023-05-04 00:06 UTC, gudominguete commented on lib/Screens/MemoryGamePage/memory_game_body.dart
> +    for (int i = 0; i < 4;) {
Tbm parametrizar o 4, talvez pegar a variavel acima e dividir por 2

2023-05-04 00:06 UTC, gudominguete commented on lib/Screens/MemoryGamePage/memory_game_body.dart
> +                for (int i = 0; i < 2; i++) ...[
Acho que seria interessante fazer um 3x4 ou 4x4

2023-05-04 00:06 UTC, gudominguete commented on lib/Screens/MemoryGamePage/memory_game_body.dart
> +                for (int i = 4; i < 6; i++) ...[
Parametrizar os for de acordo com um vetor, para nao ficar fixo os numeros

2023-05-04 12:25 UTC, LuisRotoly commented on lib/Screens/MemoryGamePage/memory_game_body.dart
> +        angleCard[i] = pi % (2 * pi);
isso é constante pi, vem de uma biblioteca

2023-05-04 12:26 UTC, LuisRotoly commented on lib/Screens/MemoryGamePage/memory_game_body.dart
> +                for (int i = 0; i < 2; i++) ...[
é que pediram 8 cartas na tarefa, mas eu tambem preferiria mais

2023-05-04 12:30 UTC, LuisRotoly commented on lib/Screens/MemoryGamePage/memory_game_body.dart
> +  List<String> randomicTextList = List<String>.filled(8, "");
Sim, tipo pra não ser sempre as mesmas frases acho que o legal seria ter mais do que a quantidade de cartas, nesse caso pra 8 cartas eu fiz 10 frases, mas acho que quanto mais melhor

2023-05-04 22:09 UTC, gudominguete requested changes

2023-05-04 22:09 UTC, gudominguete commented on lib/Screens/MemoryGamePage/memory_game_body.dart
> +                for (int i = 0; i < (cardsQuantity * 1) ~/ 4; i++) ...[
Pq essa conta? o * 1 nao faz sentido aqui pq qualquer numero vezes 1 é igual a 1

2023-05-04 22:09 UTC, gudominguete commented on lib/Screens/MemoryGamePage/memory_game_body.dart
> +                for (int i = (cardsQuantity * 1) ~/ 4;
Remover o *1

2023-05-04 22:09 UTC, gudominguete commented on lib/Screens/MemoryGamePage/memory_game_body.dart
> +                    i < (cardsQuantity * 1) ~/ 2;
Remover o *1

2023-05-04 22:09 UTC, gudominguete commented on lib/Screens/MemoryGamePage/memory_game_body.dart
> +                for (int i = (cardsQuantity * 1) ~/ 2;
Remover o *1

2023-05-08 01:16 UTC, gudominguete approved these changes

2023-05-08 20:03 UTC, merged