Respostas questionarios incluidas no backend
LIFeSUFSCAR/APP-MENTAL pull request #33
Opened 2023-05-16 21:50 UTC by LuisRotoly

Retirados os arquivos de resposta de cada questionário
Feitas alterações para buscar as respostas no backend
Mostrar as respostas na tela a depender de cada questionário e pergunta.

2023-05-17 22:35 UTC, gudominguete requested changes

2023-05-17 22:35 UTC, gudominguete commented on lib/escalas/question_screen.dart
> +    for (var i = 0; i < answers.length; i++) {
User let

2023-05-17 22:35 UTC, gudominguete commented on lib/escalas/result_questions.dart
> +      for (var index = 0; index < values.length; index++) {
Usar let

2023-05-18 17:33 UTC, LuisRotoly commented on lib/escalas/question_screen.dart
> +    for (var i = 0; i < answers.length; i++) {
Não tem let, coloquei int

2023-05-18 17:34 UTC, LuisRotoly commented on lib/escalas/result_questions.dart
> +      for (var index = 0; index < values.length; index++) {
Não tem let, coloquei int

2023-05-18 23:55 UTC, gudominguete commented on lib/escalas/result_questions.dart
> +      for (var index = 0; index < values.length; index++) {
Eh vdd, nem precisava, mas nao tem problema hahah confundi com o React

2023-05-18 23:56 UTC, gudominguete approved these changes

2023-05-19 11:45 UTC, merged