Graficos dos questionários
LIFeSUFSCAR/APP-MENTAL pull request #37
Opened 2023-05-26 22:24 UTC by LuisRotoly

2023-05-28 02:40 UTC, gudominguete requested changes

2023-05-28 02:40 UTC, gudominguete commented on lib/Screens/Questionarie/Charts/SleepScreen/Widgets/first_card.dart
> +                Expanded(
O que seria o Expanded?

2023-05-28 02:40 UTC, gudominguete commented on lib/Screens/Questionarie/Charts/SleepScreen/Widgets/first_card.dart
> +  Widget build(BuildContext context) {
O componente ta gigante, diminui em mais componentes estáticos

2023-05-28 02:40 UTC, gudominguete commented on lib/Screens/Questionarie/Charts/SleepScreen/Widgets/second_card.dart
> +class _SecondCardState extends State<SecondCard> {
Componente está muito grande, verificar se é possível criar mais componentes estáticos e reutilizar nos outros componentes

2023-05-28 02:40 UTC, gudominguete commented on lib/Screens/Questionarie/Charts/SleepScreen/Widgets/second_card.dart
> +class SecondCard extends StatefulWidget {
Nome das classes está ruim, o que seria First e Second Card?

2023-05-28 02:40 UTC, gudominguete commented on lib/Screens/Questionarie/Charts/SleepScreen/chart_sleep_screen.dart
> +    SleepService().getSleepQuestionnaireAnswersApp("a@a.com", "2023-05-25")
Temporário?

2023-05-28 02:40 UTC, gudominguete commented on lib/Screens/Questionarie/Charts/SleepScreen/chart_sleep_screen.dart
> +        //Constants.myEmail*/
Remover?

2023-05-28 02:40 UTC, gudominguete commented on lib/Screens/Questionarie/Charts/SleepScreen/chart_sleep_screen.dart
> +            //date picker
Remover?

2023-05-28 02:40 UTC, gudominguete commented on lib/Screens/Questionarie/Charts/chart_general_screen.dart
> +  int showingTooltip = -1;
Não pode trabalhar com boolean?

2023-05-28 02:40 UTC, gudominguete commented on lib/Screens/Questionarie/Charts/chart_general_screen.dart
> +                            //interval: 2,
Remover?

2023-05-28 02:40 UTC, gudominguete commented on lib/Screens/Questionarie/Charts/chart_general_screen.dart
> +                            //axisNameWidget: Text("Questionário PN1"),
Remover?

2023-05-28 02:40 UTC, gudominguete commented on lib/Screens/Questionarie/Charts/chart_promis_screen.dart
> +  List listDominion = [
Pegar a lista de dominios do backend

2023-05-28 02:40 UTC, gudominguete commented on lib/model/sleep.dart
> +class Sleep {
Mudar o nome para SleepDiaryModel ou algo do tipo

2023-05-29 10:32 UTC, LuisRotoly commented on lib/Screens/Questionarie/Charts/SleepScreen/Widgets/first_card.dart
> +                Expanded(
É um widget que expande até o limite possivel do filho. Normalmente um widget vai usar o minimo possivel de tamanho. O expanded faz o contrario e usa o máximo possivel para aquele filho

2023-05-29 10:33 UTC, LuisRotoly commented on lib/Screens/Questionarie/Charts/SleepScreen/chart_sleep_screen.dart
> +        //Constants.myEmail*/
Temporário

2023-05-29 10:34 UTC, LuisRotoly commented on lib/Screens/Questionarie/Charts/SleepScreen/chart_sleep_screen.dart
> +    SleepService().getSleepQuestionnaireAnswersApp("a@a.com", "2023-05-25")
Sim, eu estava usando na main pra ir direto pra essa página

2023-05-29 10:34 UTC, LuisRotoly commented on lib/Screens/Questionarie/Charts/SleepScreen/chart_sleep_screen.dart
> +            //date picker
Temporário

2023-05-30 13:33 UTC, LuisRotoly commented on lib/Screens/Questionarie/Charts/SleepScreen/Widgets/second_card.dart
> +class SecondCard extends StatefulWidget {
Esse é o problema eu não sei que nome dar. Os nomes estão se referindo aos blocos com todos os dados. Tem o primeiro bloco e o segundo. Tem alguma ideia de nome pra me ajudar?

2023-05-30 13:40 UTC, LuisRotoly commented on lib/Screens/Questionarie/Charts/chart_general_screen.dart
> +  int showingTooltip = -1;
Removido

2023-05-30 13:42 UTC, LuisRotoly commented on lib/Screens/Questionarie/Charts/chart_promis_screen.dart
> +  List listDominion = [
Não temos nada disso no backend, só tenho as numerações do dominio em cada pergunta que foram inseridas no banco de dados.

2023-05-31 00:38 UTC, gudominguete commented on lib/Screens/Questionarie/Charts/SleepScreen/Widgets/second_card.dart
> +class SecondCard extends StatefulWidget {
Pega o nome do conjunto dos dados, eu nao sei de cor o q tem em cada um, mas pode ate colocar SleepDiaryGraphicCard e outros

2023-05-31 00:42 UTC, gudominguete commented on lib/Screens/Questionarie/Charts/chart_promis_screen.dart
> +  List listDominion = [
Então como é fixo, pode mandar pro backend

2023-05-31 01:00 UTC, gudominguete requested changes

2023-05-31 01:00 UTC, gudominguete commented on lib/Screens/Questionarie/Charts/SleepScreen/Widgets/date_picker.dart
> +      firstDate: DateTime(2000),
Pq essas datas?

2023-05-31 01:00 UTC, gudominguete commented on lib/Screens/Questionarie/Charts/SleepScreen/Widgets/date_picker.dart
> +        DateFormat("dd/MM/yyyy").format(
Criar uma constante com os formatos de datas

2023-05-31 01:00 UTC, gudominguete commented on lib/Screens/Questionarie/Charts/SleepScreen/Widgets/first_card.dart
> +  Widget build(BuildContext context) {
Pode diminuir mais D:

2023-05-31 01:00 UTC, gudominguete commented on lib/Screens/Questionarie/Charts/chart_substance_screen.dart
> +  List listSubstance = [
Colocar dominio no backend

2023-05-31 01:00 UTC, gudominguete commented on lib/Screens/Questionarie/Charts/chart_week_screen.dart
> +                      generateGroupData(0, 1),
Ta fixo temporario ne?

2023-05-31 01:00 UTC, gudominguete commented on lib/Screens/Questionarie/Widgets/all_quest_room_tile.dart
> +          //chart substances
remover?

2023-05-31 01:00 UTC, gudominguete commented on lib/Screens/Questionarie/Widgets/all_quiz_card.dart
> +class AllQuizCard extends StatelessWidget {
Talvez GenericQuizCard seria melhor

2023-05-31 01:00 UTC, gudominguete commented on lib/main.dart
> +  /*initializeDateFormatting('pt_BR', null).then(
descomentar

2023-05-31 13:36 UTC, LuisRotoly commented on lib/Screens/Questionarie/Charts/chart_week_screen.dart
> +                      generateGroupData(0, 1),
Eu preciso da isa me mandar o layout, por enquanto esquece esse arquivo

2023-05-31 13:40 UTC, LuisRotoly commented on lib/main.dart
> +  /*initializeDateFormatting('pt_BR', null).then(
Na verdade eu removi ele, logo abaixo eu usei uma outra função no MaterialApp pra deixar global o ptbr tanto pra android quanto pra ios.
Do jeito que estava antes não mudava o datepicker para ptbr

2023-05-31 13:43 UTC, LuisRotoly commented on lib/Screens/Questionarie/Charts/SleepScreen/Widgets/date_picker.dart
> +      firstDate: DateTime(2000),
Essas datas são necessárias para criar o datepicker. Tem uma data inicial (ultimo dia que o usuário respondeu o questionário) que é a data que o calendário vai abrir, tem o máximo (2000) e o mínimo (2101).

2023-05-31 14:09 UTC, LuisRotoly commented on lib/Screens/Questionarie/Charts/chart_substance_screen.dart
> +  List listSubstance = [
Depois a gente debate sobre

2023-06-01 01:41 UTC, gudominguete requested changes

2023-06-01 01:41 UTC, gudominguete commented on lib/Screens/Questionarie/Charts/SleepScreen/Widgets/date_picker.dart
> +      firstDate: DateTime(2000),
Mas esse é o ano?  Vc conferiu quais datas ele retorna? Melhor colocar a data completo pra ficar mais facil de ler

2023-06-01 12:04 UTC, LuisRotoly commented on lib/Screens/Questionarie/Charts/SleepScreen/Widgets/date_picker.dart
> +      firstDate: DateTime(2000),
sim esse é o ano de começo. Ele retorna as datas desde primeiro de janeiro. Mas eu altero pra colocar a data por inteiro

2023-06-01 23:34 UTC, gudominguete approved these changes

2023-06-09 19:26 UTC, merged