Novo layout materiais educativos
LIFeSUFSCAR/APP-MENTAL pull request #38
Opened 2023-06-02 17:11 UTC by LuisRotoly

Adequações feitas para seguir o novo layout.
Scroll horizontal nos materiais relacionados
Aguardando para ver como serão inseridas as imagens no card
![Screenshot_2023-06-02-13-44-29-094_com ufscar app_mental](https://github.com/LIFeSUFSCAR/APP-MENTAL/assets/109184689/f922fd01-bd74-4b59-9efb-58514ff1bba8)

![Screenshot_2023-06-02-13-27-42-208_com ufscar app_mental](https://github.com/LIFeSUFSCAR/APP-MENTAL/assets/109184689/78385011-f732-4b79-b3b1-66f19a46de0e)

2023-06-05 22:36 UTC, gudominguete commented on lib/Screens/Reading/Widgets/group_reading_card.dart
> +                    Text("image"),
Aqui vai mudar ainda?

2023-06-06 10:53 UTC, LuisRotoly commented on lib/Screens/Reading/Widgets/group_reading_card.dart
> +                    Text("image"),
sim, tem algmas alterações que dependiam de como eu ia fazer no dashboard

2023-06-08 00:57 UTC, gudominguete approved these changes

2023-06-12 23:29 UTC, gudominguete requested changes

2023-06-12 23:29 UTC, gudominguete commented on lib/Screens/Reading/Text/Widgets/text_body.dart
> +                    ? Column(
Cria um componente só pro slider e chama aqui

2023-06-12 23:29 UTC, gudominguete commented on lib/Screens/Reading/Text/text_screen.dart
> +      for (int i = 0; i < widget.relatedReadings!.length; i++) {
Usar o foreach

2023-06-12 23:29 UTC, gudominguete commented on lib/Screens/Reading/Text/text_screen.dart
> +        await ReadingDatabase.instance
Busca todas as readings de uma vez, se fizer desse jeito será mais lento pq cada iteração ele irá abrir uma conexao com o db e fazer todo o processo, cria uma query que receba todos os ids e retorna todos os readings

2023-06-12 23:29 UTC, gudominguete commented on lib/model/reading_image_carousel.dart
> +    this.id,
id tbm é required, não?

2023-06-15 12:01 UTC, gudominguete approved these changes

2023-06-15 17:07 UTC, merged