Alterações de questionários feitas no app
LIFeSUFSCAR/APP-MENTAL pull request #43
Opened 2023-06-20 21:25 UTC by LuisRotoly

Alterações dos questionários pn1, pn2, pn2A e inclusão dos questionários Quesi e Copsoq.

2023-06-20 22:19 UTC, gudominguete requested changes

2023-06-20 22:19 UTC, gudominguete commented on lib/Screens/Questionarie/Charts/chart_promis_screen.dart
> +    getLegend(QuestionnaireCode.ccsm.name);
Mudar o nome do arquivo

2023-06-20 22:19 UTC, gudominguete commented on lib/escalas/question_screen.dart
> +    if (answer == "Não" && questionnaireCode == "quesi") {
Como que vem essa answer? sempre string?

2023-06-20 22:19 UTC, gudominguete commented on lib/escalas/question_screen.dart
> +    if (answer == "Não" && questionnaireCode == "quesi") {
Eu trocaria a comparação tbm, no caso colocar o questionnaireCode == "quesi" primeiro.  O ponto é que se a primeira comparação não der certo, eles nem verificam a segunda. Acredito que faz mais sentido verificar qual o questionário primeiro

2023-06-21 22:15 UTC, LuisRotoly commented on lib/escalas/question_screen.dart
> +    if (answer == "Não" && questionnaireCode == "quesi") {
Sim sempre string

2023-06-21 22:40 UTC, gudominguete commented on lib/escalas/question_screen.dart
> +    if (answer == "Não" && questionnaireCode == "quesi") {
no caso não é mudar a logica, é fazer isso:

`if (questionnaireCode == "quesi" && answer == "Não" ) {`

2023-06-23 00:04 UTC, gudominguete approved these changes

2023-06-23 12:50 UTC, merged