Criado botão para atualizar leituras e leitura sem internet funcionando
LIFeSUFSCAR/APP-MENTAL pull request #57
Opened 2023-07-28 17:20 UTC by LuisRotoly

Aparece o snackBar no home e na tela inicial da leitura
![WhatsApp Image 2023-07-28 at 14 14 05](https://github.com/LIFeSUFSCAR/APP-MENTAL/assets/109184689/ac4a7dd2-9f82-4f7e-ac0e-085cd1dd4216)

Botão para atualizar as leituras
![WhatsApp Image 2023-07-28 at 14 19 25](https://github.com/LIFeSUFSCAR/APP-MENTAL/assets/109184689/7fe24b8a-fb29-482f-838e-dfb9611535e8)

2023-07-31 01:51 UTC, gudominguete requested changes

2023-07-31 01:51 UTC, gudominguete commented on lib/Screens/Reading/recomended_readings.dart
> +      content: Text("Erro ao tentar se conectar com o servidor!",
O texto deve vir do backend

2023-07-31 01:51 UTC, gudominguete commented on lib/Services/userService.dart
> +    final response = await Api().get("verifyUserConection");
O que essa function vai fazer?

2023-07-31 10:39 UTC, LuisRotoly commented on lib/Services/userService.dart
> +    final response = await Api().get("verifyUserConection");
Respondi no backend

2023-07-31 10:39 UTC, LuisRotoly commented on lib/Screens/Reading/recomended_readings.dart
> +      content: Text("Erro ao tentar se conectar com o servidor!",
Como vai vir o texto do backend se o usuário não tem conexão?

2023-07-31 12:27 UTC, gudominguete commented on lib/Screens/Reading/recomended_readings.dart
> +      content: Text("Erro ao tentar se conectar com o servidor!",
Vdd!

2023-08-01 02:34 UTC, gudominguete requested changes

2023-08-01 02:34 UTC, gudominguete commented on lib/Screens/Reading/recomended_readings.dart
> +    await ReadingService()
Coloca chamando dentro do callback do getReadings

2023-08-01 02:34 UTC, gudominguete commented on lib/Services/userService.dart
> +    final response = await Api().get("verifyUserConection");
Pode deletar aqui né?

2023-08-01 16:55 UTC, gudominguete approved these changes

2023-08-01 16:56 UTC, merged